/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simuladorcompteo;

import java.util.ArrayList;

public class OperationsFrame extends javax.swing.JFrame {

    ArrayList<String> entry = new ArrayList<>();
    ArrayList<String> output = new ArrayList<>();

    public ArrayList<String> getEntry() {
        return entry;
    }

    public void setEntry(ArrayList<String> entry) {
        this.entry = entry;
    }

    public ArrayList<String> getOutput() {
        return output;
    }

    public void setOutput(ArrayList<String> output) {
        this.output = output;
    }

    public OperationsFrame() {

        initComponents();
        hideBoxes();

    }

    public void hideBoxes() {
        jComboBoxOpertions1.setVisible(false);
        jComboBoxOpertions2.setVisible(false);
        jComboBoxOpertions3.setVisible(false);
        jComboBoxOpertions4.setVisible(false);
        jComboBoxOpertions5.setVisible(false);
        jComboBoxOpertions6.setVisible(false);
        jComboBoxOpertions7.setVisible(false);
        jComboBoxOpertions8.setVisible(false);
        jComboBoxOpertions9.setVisible(false);
        jComboBoxOpertions10.setVisible(false);
        jComboBoxOpertions11.setVisible(false);
        jComboBoxOpertions12.setVisible(false);
        jComboBoxOpertions13.setVisible(false);
        jComboBoxOpertions14.setVisible(false);
        jComboBoxOpertions15.setVisible(false);
        jComboBoxOpertions16.setVisible(false);

    }

    public void showBoxes() {
        if (!entry.isEmpty()) {
            jComboBoxOpertions1.setVisible(true);
        }
        if (entry.size() > 1) {
            jComboBoxOpertions2.setVisible(true);
        }
        if (entry.size() > 2) {
            jComboBoxOpertions3.setVisible(true);
        }
        if (entry.size() > 3) {
            jComboBoxOpertions4.setVisible(true);
        }
        if (entry.size() > 4) {
            jComboBoxOpertions5.setVisible(true);
        }
        if (entry.size() > 5) {
            jComboBoxOpertions6.setVisible(true);
        }
        if (entry.size() > 6) {
            jComboBoxOpertions7.setVisible(true);
        }
        if (entry.size() > 7) {
            jComboBoxOpertions8.setVisible(true);
        }
        if (entry.size() > 8) {
            jComboBoxOpertions9.setVisible(true);
        }
        if (entry.size() > 9) {
            jComboBoxOpertions10.setVisible(true);
        }
        if (entry.size() > 10) {
            jComboBoxOpertions11.setVisible(true);
        }
        if (entry.size() > 11) {
            jComboBoxOpertions12.setVisible(true);
        }
        if (entry.size() > 12) {
            jComboBoxOpertions13.setVisible(true);
        }
        if (entry.size() > 13) {
            jComboBoxOpertions14.setVisible(true);
        }
        if (entry.size() > 14) {
            jComboBoxOpertions15.setVisible(true);
        }
        if (entry.size() > 15) {
            jComboBoxOpertions16.setVisible(true);
        }

    }

    public void hideAdditionalBoxes() {
        //operation 1
        jComboBoxEntry1.setVisible(false);
        jComboBoxSecondEntry1.setVisible(false);
        jComboBoxOut1.setVisible(false);
    }

    public void showAdditionalBoxes() {
        if (jComboBoxOpertions1.isVisible()) {
            jComboBoxEntry1.setVisible(true);
            if (jComboBoxOpertions1.getSelectedItem() == "Soma") {
                jComboBoxSecondEntry1.setVisible(true);
                jComboBoxOut1.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxOpertions1 = new javax.swing.JComboBox<>();
        jComboBoxOpertions2 = new javax.swing.JComboBox<>();
        jComboBoxOpertions3 = new javax.swing.JComboBox<>();
        jComboBoxOpertions4 = new javax.swing.JComboBox<>();
        jComboBoxOpertions5 = new javax.swing.JComboBox<>();
        jComboBoxOpertions6 = new javax.swing.JComboBox<>();
        jComboBoxOpertions7 = new javax.swing.JComboBox<>();
        jComboBoxOpertions8 = new javax.swing.JComboBox<>();
        jComboBoxOpertions9 = new javax.swing.JComboBox<>();
        jComboBoxOpertions10 = new javax.swing.JComboBox<>();
        jComboBoxOpertions11 = new javax.swing.JComboBox<>();
        jComboBoxOpertions12 = new javax.swing.JComboBox<>();
        jComboBoxOpertions13 = new javax.swing.JComboBox<>();
        jComboBoxOpertions14 = new javax.swing.JComboBox<>();
        jComboBoxOpertions15 = new javax.swing.JComboBox<>();
        jComboBoxOpertions16 = new javax.swing.JComboBox<>();
        jComboBoxEntry1 = new javax.swing.JComboBox<>();
        jComboBoxSecondEntry1 = new javax.swing.JComboBox<>();
        jComboBoxOut1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxOpertions1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));
        jComboBoxOpertions1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpertions1ActionPerformed(evt);
            }
        });

        jComboBoxOpertions2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));
        jComboBoxOpertions2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpertions2ActionPerformed(evt);
            }
        });

        jComboBoxOpertions3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));
        jComboBoxOpertions3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpertions3ActionPerformed(evt);
            }
        });

        jComboBoxOpertions4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));
        jComboBoxOpertions4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpertions4ActionPerformed(evt);
            }
        });

        jComboBoxOpertions5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));
        jComboBoxOpertions5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpertions5ActionPerformed(evt);
            }
        });

        jComboBoxOpertions6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jComboBoxOpertions16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soma", "-1", "+1", "^2" }));

        jLabel1.setText("Saida:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxOpertions8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxOpertions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBoxEntry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSecondEntry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxOpertions16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpertions9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxOpertions9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxOpertions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEntry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSecondEntry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxOut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOpertions2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxOpertions8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOpertions1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpertions1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpertions1ActionPerformed

    private void jComboBoxOpertions2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpertions2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpertions2ActionPerformed

    private void jComboBoxOpertions3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpertions3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpertions3ActionPerformed

    private void jComboBoxOpertions4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpertions4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpertions4ActionPerformed

    private void jComboBoxOpertions5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpertions5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpertions5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperationsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxEntry1;
    private javax.swing.JComboBox<String> jComboBoxOpertions1;
    private javax.swing.JComboBox<String> jComboBoxOpertions10;
    private javax.swing.JComboBox<String> jComboBoxOpertions11;
    private javax.swing.JComboBox<String> jComboBoxOpertions12;
    private javax.swing.JComboBox<String> jComboBoxOpertions13;
    private javax.swing.JComboBox<String> jComboBoxOpertions14;
    private javax.swing.JComboBox<String> jComboBoxOpertions15;
    private javax.swing.JComboBox<String> jComboBoxOpertions16;
    private javax.swing.JComboBox<String> jComboBoxOpertions2;
    private javax.swing.JComboBox<String> jComboBoxOpertions3;
    private javax.swing.JComboBox<String> jComboBoxOpertions4;
    private javax.swing.JComboBox<String> jComboBoxOpertions5;
    private javax.swing.JComboBox<String> jComboBoxOpertions6;
    private javax.swing.JComboBox<String> jComboBoxOpertions7;
    private javax.swing.JComboBox<String> jComboBoxOpertions8;
    private javax.swing.JComboBox<String> jComboBoxOpertions9;
    private javax.swing.JComboBox<String> jComboBoxOut1;
    private javax.swing.JComboBox<String> jComboBoxSecondEntry1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
