/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simuladorcompteo;

import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuário
 */
public class SimulatorFrame extends javax.swing.JFrame {

    String machineName = "";
    int entryR = 0;
    int outR = 0;
    int tableControl = 0;
    int regNum = 0;
    
    String allEntryRegisters;
    String allOutRegisters;
    
    
    DefaultListModel listModel = new DefaultListModel();

    ArrayList<String> entryArray = new ArrayList<>();
    ArrayList<String> outArray = new ArrayList<>();
    //Hashtable<Integer, String> entryReg = new Hashtable<>();
    //Hashtable<Integer, String> outReg = new Hashtable<>();

    public void setListModel(DefaultListModel listModel) {
        this.listModel = listModel;
    }

    public ArrayList<String> getEntryArray() {
        return entryArray;
    }

    public ArrayList<String> getOutArray() {
        return outArray;
    }

    
        public void buildStringEntries() {
        StringBuilder stb = new StringBuilder();
        allEntryRegisters = "";
        int i = 0;
        //for(int i = 0; i < entry.size(); i++){
        while (i < entryArray.size()) {
            allEntryRegisters = allEntryRegisters + entryArray.get(i);
            i++;
            if (i < entryArray.size()) {
                allEntryRegisters = allEntryRegisters + ",";
            }

        }
        System.out.println(allEntryRegisters);

    }

    public void buildStringOutput() {
        StringBuilder stb = new StringBuilder();
        allOutRegisters = "";
        int i = 0;
        //for(int i = 0; i < entry.size(); i++){
        while (i < outArray.size()) {
            allOutRegisters = allOutRegisters + outArray.get(i);
            i++;
            if (i < outArray.size()) {
                allOutRegisters = allOutRegisters + ",";
            }

        }
        System.out.println(allOutRegisters);

    }
    
        public String stringMaker() {

        String s = "Armazena : N" + entryArray.size() + " -> N" + jComboBoxNumberRegisters.getSelectedItem()
                + " tal que, ∀ " + allEntryRegisters + "∈N Armazena_" + machineName + "(" + allEntryRegisters
                + ")";
        return s;
    }

    public String stringMakerReturn() {
        String s = "Retorna" + ": N" + jComboBoxNumberRegisters.getSelectedItem() + " -> N" + outArray.size()
                + " tal que, ∀ " + allOutRegisters + "∈N Retorna_" + machineName + "(" + allEntryRegisters
                + ")";
        return s;
    }
    
    public SimulatorFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegNum = new javax.swing.JLabel();
        jComboBoxNumberRegisters = new javax.swing.JComboBox<>();
        jRadioButtonAEntrada = new javax.swing.JRadioButton();
        jRadioButtonBEntrada = new javax.swing.JRadioButton();
        jRadioButtonCEntrada = new javax.swing.JRadioButton();
        jRadioButtonDEntrada = new javax.swing.JRadioButton();
        jRadioButtonEEntrada = new javax.swing.JRadioButton();
        jRadioButtonFEntrada = new javax.swing.JRadioButton();
        jRadioButtonGEntrada = new javax.swing.JRadioButton();
        jRadioButtonHEntrada = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonFSaida = new javax.swing.JRadioButton();
        jRadioButtonGSaida = new javax.swing.JRadioButton();
        jRadioButtonHSaida = new javax.swing.JRadioButton();
        jRadioButtonASaida = new javax.swing.JRadioButton();
        jRadioButtonBSaida = new javax.swing.JRadioButton();
        jRadioButtonCSaida = new javax.swing.JRadioButton();
        jRadioButtonDSaida = new javax.swing.JRadioButton();
        jRadioButtonESaida = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelRegisterNumber = new javax.swing.JLabel();
        jRadioButtonPEntrada = new javax.swing.JRadioButton();
        jRadioButtonIEntrada = new javax.swing.JRadioButton();
        jRadioButtonJEntrada = new javax.swing.JRadioButton();
        jRadioButtonKEntrada = new javax.swing.JRadioButton();
        jRadioButtonLEntrada = new javax.swing.JRadioButton();
        jRadioButtonMEntrada = new javax.swing.JRadioButton();
        jRadioButtonNEntrada = new javax.swing.JRadioButton();
        jRadioButtonOEntrada = new javax.swing.JRadioButton();
        jRadioButtonNSaida = new javax.swing.JRadioButton();
        jRadioButtonOSaida = new javax.swing.JRadioButton();
        jRadioButtonPSaida = new javax.swing.JRadioButton();
        jRadioButtonISaida = new javax.swing.JRadioButton();
        jRadioButtonJSaida = new javax.swing.JRadioButton();
        jRadioButtonKSaida = new javax.swing.JRadioButton();
        jRadioButtonLSaida = new javax.swing.JRadioButton();
        jRadioButtonMSaida = new javax.swing.JRadioButton();
        jLabelMachineName = new javax.swing.JLabel();
        jTextFieldMachineName = new javax.swing.JTextField();
        jButtonMachineName = new javax.swing.JButton();
        jLabelConjuntos = new javax.swing.JLabel();
        jLabelREntrada = new javax.swing.JLabel();
        jLabelRSaida = new javax.swing.JLabel();
        jButtonOperations = new javax.swing.JButton();
        jLabelEntrada = new javax.swing.JLabel();
        jLabelSaida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRegNum.setText("Número de Registradores:  ");

        jComboBoxNumberRegisters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        jComboBoxNumberRegisters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumberRegistersActionPerformed(evt);
            }
        });

        jRadioButtonAEntrada.setText("A");
        jRadioButtonAEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAEntradaActionPerformed(evt);
            }
        });

        jRadioButtonBEntrada.setText("B");
        jRadioButtonBEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBEntradaActionPerformed(evt);
            }
        });

        jRadioButtonCEntrada.setText("C");
        jRadioButtonCEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCEntradaActionPerformed(evt);
            }
        });

        jRadioButtonDEntrada.setText("D");
        jRadioButtonDEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDEntradaActionPerformed(evt);
            }
        });

        jRadioButtonEEntrada.setText("E");
        jRadioButtonEEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEEntradaActionPerformed(evt);
            }
        });

        jRadioButtonFEntrada.setText("F");
        jRadioButtonFEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFEntradaActionPerformed(evt);
            }
        });

        jRadioButtonGEntrada.setText("G");
        jRadioButtonGEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGEntradaActionPerformed(evt);
            }
        });

        jRadioButtonHEntrada.setText("H");
        jRadioButtonHEntrada.setToolTipText("");
        jRadioButtonHEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHEntradaActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha os registradores de entrada de dados:");

        jRadioButtonFSaida.setText("F");
        jRadioButtonFSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFSaidaActionPerformed(evt);
            }
        });

        jRadioButtonGSaida.setText("G");
        jRadioButtonGSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGSaidaActionPerformed(evt);
            }
        });

        jRadioButtonHSaida.setText("H");
        jRadioButtonHSaida.setToolTipText("");
        jRadioButtonHSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHSaidaActionPerformed(evt);
            }
        });

        jRadioButtonASaida.setText("A");
        jRadioButtonASaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonASaidaActionPerformed(evt);
            }
        });

        jRadioButtonBSaida.setText("B");
        jRadioButtonBSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBSaidaActionPerformed(evt);
            }
        });

        jRadioButtonCSaida.setText("C");
        jRadioButtonCSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCSaidaActionPerformed(evt);
            }
        });

        jRadioButtonDSaida.setText("D");
        jRadioButtonDSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDSaidaActionPerformed(evt);
            }
        });

        jRadioButtonESaida.setText("E");
        jRadioButtonESaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonESaidaActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha os registradores de saída de dados:");

        jLabelRegisterNumber.setText("Nome");

        jRadioButtonPEntrada.setText("P");
        jRadioButtonPEntrada.setToolTipText("");
        jRadioButtonPEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPEntradaActionPerformed(evt);
            }
        });

        jRadioButtonIEntrada.setText("I");
        jRadioButtonIEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIEntradaActionPerformed(evt);
            }
        });

        jRadioButtonJEntrada.setText("J");
        jRadioButtonJEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJEntradaActionPerformed(evt);
            }
        });

        jRadioButtonKEntrada.setText("K");
        jRadioButtonKEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKEntradaActionPerformed(evt);
            }
        });

        jRadioButtonLEntrada.setText("L");
        jRadioButtonLEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLEntradaActionPerformed(evt);
            }
        });

        jRadioButtonMEntrada.setText("M");
        jRadioButtonMEntrada.setToolTipText("");
        jRadioButtonMEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMEntradaActionPerformed(evt);
            }
        });

        jRadioButtonNEntrada.setText("N");
        jRadioButtonNEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNEntradaActionPerformed(evt);
            }
        });

        jRadioButtonOEntrada.setText("O");
        jRadioButtonOEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOEntradaActionPerformed(evt);
            }
        });

        jRadioButtonNSaida.setText("N");
        jRadioButtonNSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNSaidaActionPerformed(evt);
            }
        });

        jRadioButtonOSaida.setText("O");
        jRadioButtonOSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOSaidaActionPerformed(evt);
            }
        });

        jRadioButtonPSaida.setText("P");
        jRadioButtonPSaida.setToolTipText("");
        jRadioButtonPSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPSaidaActionPerformed(evt);
            }
        });

        jRadioButtonISaida.setText("I");
        jRadioButtonISaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonISaidaActionPerformed(evt);
            }
        });

        jRadioButtonJSaida.setText("J");
        jRadioButtonJSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJSaidaActionPerformed(evt);
            }
        });

        jRadioButtonKSaida.setText("K");
        jRadioButtonKSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKSaidaActionPerformed(evt);
            }
        });

        jRadioButtonLSaida.setText("L");
        jRadioButtonLSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLSaidaActionPerformed(evt);
            }
        });

        jRadioButtonMSaida.setText("M");
        jRadioButtonMSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMSaidaActionPerformed(evt);
            }
        });

        jLabelMachineName.setText("Nome da Máquina:");

        jButtonMachineName.setText("OK");
        jButtonMachineName.setToolTipText("");
        jButtonMachineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMachineNameActionPerformed(evt);
            }
        });

        jLabelConjuntos.setText("N = Conjuntos de Memória");

        jLabelREntrada.setText("N = Conjuntos de Memória");

        jLabelRSaida.setText("N = Conjuntos de Memória");

        jButtonOperations.setText("Operations");
        jButtonOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperationsActionPerformed(evt);
            }
        });

        jLabelEntrada.setText("Entrada");

        jLabelSaida.setText("Saida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButtonMachineName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jButtonOperations))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabelRegisterNumber))
                            .addComponent(jLabelREntrada)
                            .addComponent(jLabelConjuntos)
                            .addComponent(jLabelRSaida)
                            .addComponent(jLabelEntrada)
                            .addComponent(jLabelSaida)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonAEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonBEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonCEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonEEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonFEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonGEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonHEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonIEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonJEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonKEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonLEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonMEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonOEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPEntrada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonASaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonBSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonCSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonESaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonFSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonGSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonHSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonISaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonJSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonKSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonLSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonMSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonOSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonPSaida))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelMachineName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldMachineName))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelRegNum)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxNumberRegisters, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumberRegisters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegNum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMachineName)
                    .addComponent(jTextFieldMachineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAEntrada)
                    .addComponent(jRadioButtonBEntrada)
                    .addComponent(jRadioButtonCEntrada)
                    .addComponent(jRadioButtonDEntrada)
                    .addComponent(jRadioButtonEEntrada)
                    .addComponent(jRadioButtonFEntrada)
                    .addComponent(jRadioButtonGEntrada)
                    .addComponent(jRadioButtonHEntrada)
                    .addComponent(jRadioButtonIEntrada)
                    .addComponent(jRadioButtonJEntrada)
                    .addComponent(jRadioButtonKEntrada)
                    .addComponent(jRadioButtonLEntrada)
                    .addComponent(jRadioButtonMEntrada)
                    .addComponent(jRadioButtonNEntrada)
                    .addComponent(jRadioButtonOEntrada)
                    .addComponent(jRadioButtonPEntrada))
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonASaida)
                    .addComponent(jRadioButtonBSaida)
                    .addComponent(jRadioButtonCSaida)
                    .addComponent(jRadioButtonDSaida)
                    .addComponent(jRadioButtonESaida)
                    .addComponent(jRadioButtonFSaida)
                    .addComponent(jRadioButtonGSaida)
                    .addComponent(jRadioButtonHSaida)
                    .addComponent(jRadioButtonISaida)
                    .addComponent(jRadioButtonJSaida)
                    .addComponent(jRadioButtonKSaida)
                    .addComponent(jRadioButtonLSaida)
                    .addComponent(jRadioButtonMSaida)
                    .addComponent(jRadioButtonNSaida)
                    .addComponent(jRadioButtonOSaida)
                    .addComponent(jRadioButtonPSaida))
                .addGap(57, 57, 57)
                .addComponent(jButtonMachineName)
                .addGap(18, 18, 18)
                .addComponent(jLabelRegisterNumber)
                .addGap(7, 7, 7)
                .addComponent(jLabelConjuntos)
                .addGap(11, 11, 11)
                .addComponent(jLabelREntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSaida)
                .addGap(18, 18, 18)
                .addComponent(jButtonOperations)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAEntradaActionPerformed
        if (jRadioButtonAEntrada.isSelected()) {
            entryR++;
            tableControl++;
            entryArray.add("a");

            // entryReg.put(1, "a");
        } else {
            entryR--;
            tableControl--;
            // entryReg.remove(1);
            entryArray.remove("a");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonAEntradaActionPerformed
    private void jRadioButtonBEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBEntradaActionPerformed
        if (jRadioButtonBEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(2, "b");
            entryArray.add("b");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(2);
            entryArray.remove("b");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonBEntradaActionPerformed

    private void setLabelRegisterNumber(int num) {
        if (num == 1) {
            jLabelRegisterNumber.setText("um_reg");
        }
        if (num == 2) {
            jLabelRegisterNumber.setText("dois_reg");
        }
        if (num == 3) {
            jLabelRegisterNumber.setText("tres_reg");
        }
        if (num == 4) {
            jLabelRegisterNumber.setText("quatro_reg");
        }
        if (num == 5) {
            jLabelRegisterNumber.setText("cinco_reg");
        }
        if (num == 6) {
            jLabelRegisterNumber.setText("seis_reg");
        }

        if (num == 7) {
            jLabelRegisterNumber.setText("sete_reg");
        }
        if (num == 8) {
            jLabelRegisterNumber.setText("oito_reg");
        }
        if (num == 9) {
            jLabelRegisterNumber.setText("nove_reg");
        }
        if (num == 10) {
            jLabelRegisterNumber.setText("dez_reg");
        }
        if (num == 11) {
            jLabelRegisterNumber.setText("onze_reg");
        }
        if (num == 12) {
            jLabelRegisterNumber.setText("doze_reg");
        }
        if (num == 13) {
            jLabelRegisterNumber.setText("treze_reg");
        }
        if (num == 14) {
            jLabelRegisterNumber.setText("quatorze_reg");
        }
        if (num == 15) {
            jLabelRegisterNumber.setText("quinze_reg");
        }
        if (num == 16) {
            jLabelRegisterNumber.setText("dezeseis_reg");
        }

    }

    private void buttonRegVisibility(int num) {

        if (num > 0) {
            jRadioButtonAEntrada.setVisible(true);
            jRadioButtonASaida.setVisible(true);
        } else {
            jRadioButtonAEntrada.setVisible(false);
            jRadioButtonASaida.setVisible(false);
        }
        if (num > 1) {
            jRadioButtonBEntrada.setVisible(true);
            jRadioButtonBSaida.setVisible(true);
        } else {
            jRadioButtonBEntrada.setVisible(false);
            jRadioButtonBSaida.setVisible(false);
        }
        if (num > 2) {
            jRadioButtonCEntrada.setVisible(true);
            jRadioButtonCSaida.setVisible(true);
        } else {
            jRadioButtonCEntrada.setVisible(false);
            jRadioButtonCSaida.setVisible(false);
        }
        if (num > 3) {
            jRadioButtonDEntrada.setVisible(true);
            jRadioButtonDSaida.setVisible(true);
        } else {
            jRadioButtonDEntrada.setVisible(false);
            jRadioButtonDSaida.setVisible(false);
        }
        if (num > 4) {
            jRadioButtonEEntrada.setVisible(true);
            jRadioButtonESaida.setVisible(true);
        } else {
            jRadioButtonEEntrada.setVisible(false);
            jRadioButtonESaida.setVisible(false);
        }
        if (num > 5) {
            jRadioButtonFEntrada.setVisible(true);
            jRadioButtonFSaida.setVisible(true);
        } else {
            jRadioButtonFEntrada.setVisible(false);
            jRadioButtonFSaida.setVisible(false);
        }
        if (num > 6) {
            jRadioButtonGEntrada.setVisible(true);
            jRadioButtonGSaida.setVisible(true);
        } else {
            jRadioButtonGEntrada.setVisible(false);
            jRadioButtonGSaida.setVisible(false);
        }
        if (num > 7) {
            jRadioButtonHEntrada.setVisible(true);
            jRadioButtonHSaida.setVisible(true);
        } else {
            jRadioButtonHEntrada.setVisible(false);
            jRadioButtonHSaida.setVisible(false);
        }
        if (num > 8) {
            jRadioButtonIEntrada.setVisible(true);
            jRadioButtonISaida.setVisible(true);
        } else {
            jRadioButtonIEntrada.setVisible(false);
            jRadioButtonISaida.setVisible(false);
        }
        if (num > 9) {
            jRadioButtonJEntrada.setVisible(true);
            jRadioButtonJSaida.setVisible(true);
        } else {
            jRadioButtonJEntrada.setVisible(false);
            jRadioButtonJSaida.setVisible(false);
        }
        if (num > 10) {
            jRadioButtonKEntrada.setVisible(true);
            jRadioButtonKSaida.setVisible(true);
        } else {
            jRadioButtonKEntrada.setVisible(false);
            jRadioButtonKSaida.setVisible(false);
        }
        if (num > 11) {
            jRadioButtonLEntrada.setVisible(true);
            jRadioButtonLSaida.setVisible(true);
        } else {
            jRadioButtonLEntrada.setVisible(false);
            jRadioButtonLSaida.setVisible(false);
        }
        if (num > 12) {
            jRadioButtonMEntrada.setVisible(true);
            jRadioButtonMSaida.setVisible(true);
        } else {
            jRadioButtonMEntrada.setVisible(false);
            jRadioButtonMSaida.setVisible(false);
        }
        if (num > 13) {
            jRadioButtonNEntrada.setVisible(true);
            jRadioButtonNSaida.setVisible(true);
        } else {
            jRadioButtonNEntrada.setVisible(false);
            jRadioButtonNSaida.setVisible(false);
        }
        if (num > 14) {
            jRadioButtonOEntrada.setVisible(true);
            jRadioButtonOSaida.setVisible(true);
        } else {
            jRadioButtonOEntrada.setVisible(false);
            jRadioButtonOSaida.setVisible(false);
        }
        if (num > 15) {
            jRadioButtonPEntrada.setVisible(true);
            jRadioButtonPSaida.setVisible(true);
        } else {
            jRadioButtonPEntrada.setVisible(false);
            jRadioButtonPSaida.setVisible(false);
        }

    }

    private void jComboBoxNumberRegistersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumberRegistersActionPerformed
        regNum = jComboBoxNumberRegisters.getSelectedIndex();
        System.out.println(regNum);

        this.buttonRegVisibility(regNum);
        this.setLabelRegisterNumber(regNum);

        System.out.println(machineName);


    }//GEN-LAST:event_jComboBoxNumberRegistersActionPerformed

    private void jRadioButtonASaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonASaidaActionPerformed
        if (jRadioButtonASaida.isSelected()) {
            outR++;
            //outReg.put(1, "a");
            outArray.add("a");

        } else {
            outR--;
            //outReg.remove(1);
            outArray.remove("a");
        }

    }//GEN-LAST:event_jRadioButtonASaidaActionPerformed

    private void jRadioButtonBSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBSaidaActionPerformed
        if (jRadioButtonBSaida.isSelected()) {
            outR++;
            //outReg.put(2, "b");
            outArray.add("b");

        } else {
            outR--;
            //outReg.remove(2);
            outArray.remove("b");
        }
    }//GEN-LAST:event_jRadioButtonBSaidaActionPerformed

    private void jRadioButtonIEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIEntradaActionPerformed
        if (jRadioButtonIEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(9, "i");
            entryArray.add("i");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(9);
            entryArray.remove("i");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonIEntradaActionPerformed

    private void jRadioButtonJEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJEntradaActionPerformed
        if (jRadioButtonJEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(10, "j");
            entryArray.add("j");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(10);
            entryArray.remove("j");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonJEntradaActionPerformed

    private void jRadioButtonISaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonISaidaActionPerformed
        if (jRadioButtonISaida.isSelected()) {
            outR++;
            //outReg.put(9, "i");
            outArray.add("i");

        } else {
            outR--;
            //outReg.remove(9);
            outArray.remove("i");
        }
    }//GEN-LAST:event_jRadioButtonISaidaActionPerformed

    private void jRadioButtonJSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJSaidaActionPerformed
        if (jRadioButtonJSaida.isSelected()) {
            outR++;
            //outReg.put(10, "j");
            outArray.add("j");

        } else {
            outR--;
            //outReg.remove(10);
            outArray.remove("j");
        }
    }//GEN-LAST:event_jRadioButtonJSaidaActionPerformed

    private void jButtonMachineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMachineNameActionPerformed
        jLabelConjuntos.setText("N" + jComboBoxNumberRegisters.getSelectedIndex() + " = Conjuntos de Memória");
        jLabelREntrada.setText("N" + entryR + " = Conjuntos de Memória");
        System.out.println(regNum);
        jLabelRSaida.setText("N" + outR + " = Conjuntos de Memória");

        machineName = jTextFieldMachineName.getText();

        jLabelRegisterNumber.setText(machineName + " =(N" + regNum + ", N" + entryR + ", N" + outR);
        String s = stringMaker();
        String s2 = stringMakerReturn();
        jLabelEntrada.setText(s);
        jLabelSaida.setText(s2);
    }//GEN-LAST:event_jButtonMachineNameActionPerformed

    private void jRadioButtonCEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCEntradaActionPerformed
        if (jRadioButtonCEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(3, "c");
            entryArray.add("c");
        } else {
            entryR--;
            tableControl--;
            // entryReg.remove(3);
            entryArray.remove("c");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonCEntradaActionPerformed

    private void jRadioButtonDEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDEntradaActionPerformed
        if (jRadioButtonDEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(4, "d");
            entryArray.add("d");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(4);
            entryArray.remove("d");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonDEntradaActionPerformed

    private void jRadioButtonEEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEEntradaActionPerformed
        if (jRadioButtonEEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(5, "e");
            entryArray.add("e");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(5);
            entryArray.remove("e");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonEEntradaActionPerformed

    private void jRadioButtonFEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFEntradaActionPerformed
        if (jRadioButtonFEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(6, "f");
            entryArray.add("f");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(6);
            entryArray.remove("f");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonFEntradaActionPerformed

    private void jRadioButtonGEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGEntradaActionPerformed
        if (jRadioButtonGEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(7, "g");
            entryArray.add("g");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(7);
            entryArray.remove("g");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonGEntradaActionPerformed

    private void jRadioButtonHEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHEntradaActionPerformed
        if (jRadioButtonHEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(8, "h");
            entryArray.add("h");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(8);
            entryArray.remove("h");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonHEntradaActionPerformed

    private void jRadioButtonKEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKEntradaActionPerformed
        if (jRadioButtonKEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(11, "k");
            entryArray.add("k");
        } else {
            entryR--;
            tableControl--;
            // entryReg.remove(11);
            entryArray.remove("k");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonKEntradaActionPerformed

    private void jRadioButtonLEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLEntradaActionPerformed
        if (jRadioButtonLEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(12, "l");
            entryArray.add("l");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(12);
            entryArray.remove("l");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonLEntradaActionPerformed

    private void jRadioButtonMEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMEntradaActionPerformed
        if (jRadioButtonMEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(13, "m");
            entryArray.add("m");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(13);
            entryArray.remove("m");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonMEntradaActionPerformed

    private void jRadioButtonNEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNEntradaActionPerformed
        if (jRadioButtonNEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(14, "n");
            entryArray.add("n");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(14);
            entryArray.remove("n");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonNEntradaActionPerformed

    private void jRadioButtonOEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOEntradaActionPerformed
        if (jRadioButtonOEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(15, "o");
            entryArray.add("o");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(15);
            entryArray.remove("o");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonOEntradaActionPerformed

    private void jRadioButtonPEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPEntradaActionPerformed
        if (jRadioButtonPEntrada.isSelected()) {
            entryR++;
            tableControl++;
            //entryReg.put(16, "p");
            entryArray.add("p");
        } else {
            entryR--;
            tableControl--;
            //entryReg.remove(16);
            entryArray.remove("p");
        }
        System.out.println(entryR);
    }//GEN-LAST:event_jRadioButtonPEntradaActionPerformed

    private void jRadioButtonCSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCSaidaActionPerformed
        if (jRadioButtonCSaida.isSelected()) {
            outR++;
            //outReg.put(3, "c");
            outArray.add("c");

        } else {
            outR--;
            //outReg.remove(3);
            outArray.remove("c");
        }
    }//GEN-LAST:event_jRadioButtonCSaidaActionPerformed

    private void jRadioButtonDSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDSaidaActionPerformed
        if (jRadioButtonDSaida.isSelected()) {
            outR++;
            //outReg.put(4, "d");
            outArray.add("d");

        } else {
            outR--;
            //outReg.remove(4);
            outArray.remove("d");
        }
    }//GEN-LAST:event_jRadioButtonDSaidaActionPerformed

    private void jRadioButtonESaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonESaidaActionPerformed
        if (jRadioButtonESaida.isSelected()) {
            outR++;
            //outReg.put(5, "e");
            outArray.add("e");

        } else {
            outR--;
            //outReg.remove(5);
            outArray.remove("e");
        }
    }//GEN-LAST:event_jRadioButtonESaidaActionPerformed

    private void jRadioButtonFSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFSaidaActionPerformed
        if (jRadioButtonFSaida.isSelected()) {
            outR++;
            //outReg.put(6, "f");
            outArray.add("f");

        } else {
            outR--;
            //outReg.remove(6);
            outArray.remove("f");

        }
    }//GEN-LAST:event_jRadioButtonFSaidaActionPerformed

    private void jRadioButtonGSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGSaidaActionPerformed
        if (jRadioButtonGSaida.isSelected()) {
            outR++;
            //outReg.put(7, "g");
            outArray.add("g");

        } else {
            outR--;
            //outReg.remove(7);
            outArray.remove("g");
        }
    }//GEN-LAST:event_jRadioButtonGSaidaActionPerformed

    private void jRadioButtonHSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHSaidaActionPerformed
        if (jRadioButtonHSaida.isSelected()) {
            outR++;
            //outReg.put(8, "h");
            outArray.add("h");

        } else {
            outR--;
            //outReg.remove(8);
            outArray.remove("h");
        }
    }//GEN-LAST:event_jRadioButtonHSaidaActionPerformed

    private void jRadioButtonKSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKSaidaActionPerformed
        if (jRadioButtonKSaida.isSelected()) {
            outR++;
            //outReg.put(11, "k");
            outArray.add("k");

        } else {
            outR--;
            //outReg.remove(11);
            outArray.remove("k");
        }
    }//GEN-LAST:event_jRadioButtonKSaidaActionPerformed

    private void jRadioButtonLSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLSaidaActionPerformed
        if (jRadioButtonLSaida.isSelected()) {
            outR++;
            //outReg.put(12, "l");
            outArray.add("l");

        } else {
            outR--;
            //outReg.remove(12);
            outArray.remove("l");
        }
    }//GEN-LAST:event_jRadioButtonLSaidaActionPerformed

    private void jRadioButtonMSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMSaidaActionPerformed
        if (jRadioButtonMSaida.isSelected()) {
            outR++;
            //outReg.put(13, "M");
            outArray.add("m");

        } else {
            outR--;
            //outReg.remove(13);
            outArray.remove("m");

        }
    }//GEN-LAST:event_jRadioButtonMSaidaActionPerformed

    private void jRadioButtonNSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNSaidaActionPerformed
        if (jRadioButtonNSaida.isSelected()) {
            outR++;
            //outReg.put(14, "n");
            outArray.add("n");

        } else {
            outR--;
            //outReg.remove(14);
            outArray.remove("n");
        }
    }//GEN-LAST:event_jRadioButtonNSaidaActionPerformed

    private void jRadioButtonOSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOSaidaActionPerformed
        if (jRadioButtonOSaida.isSelected()) {
            outR++;
            //outReg.put(15, "o");
            outArray.add("o");

        } else {
            outR--;
            //outReg.remove(15);
            outArray.remove("o");
        }
    }//GEN-LAST:event_jRadioButtonOSaidaActionPerformed

    private void jRadioButtonPSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPSaidaActionPerformed
        if (jRadioButtonPSaida.isSelected()) {
            outR++;
            //outReg.put(16, "p");
            outArray.add("p");

        } else {
            outR--;
            //outReg.remove(16);
            outArray.remove("p");
        }
    }//GEN-LAST:event_jRadioButtonPSaidaActionPerformed

    private void jButtonOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperationsActionPerformed
        OperationsFrame operationsFrame = new OperationsFrame();
        operationsFrame.setEntry(entryArray);
        operationsFrame.setOutput(outArray);
        operationsFrame.setVisible(true);

        operationsFrame.setNumberRegs(jComboBoxNumberRegisters.getSelectedIndex());
//operationsFrame.showBoxes();
        operationsFrame.showAdditionalBoxes();
        operationsFrame.buildStringEntries();
       
        

    }//GEN-LAST:event_jButtonOperationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorFrame().setVisible(true);

                jLabelRegisterNumber.setText("zero_reg");

                jRadioButtonAEntrada.setVisible(false);
                jRadioButtonBEntrada.setVisible(false);
                jRadioButtonCEntrada.setVisible(false);
                jRadioButtonDEntrada.setVisible(false);

                jRadioButtonEEntrada.setVisible(false);
                jRadioButtonFEntrada.setVisible(false);
                jRadioButtonGEntrada.setVisible(false);
                jRadioButtonHEntrada.setVisible(false);

                jRadioButtonIEntrada.setVisible(false);
                jRadioButtonJEntrada.setVisible(false);
                jRadioButtonKEntrada.setVisible(false);
                jRadioButtonLEntrada.setVisible(false);

                jRadioButtonMEntrada.setVisible(false);
                jRadioButtonNEntrada.setVisible(false);
                jRadioButtonOEntrada.setVisible(false);
                jRadioButtonPEntrada.setVisible(false);

                jRadioButtonASaida.setVisible(false);
                jRadioButtonBSaida.setVisible(false);
                jRadioButtonCSaida.setVisible(false);
                jRadioButtonDSaida.setVisible(false);

                jRadioButtonESaida.setVisible(false);
                jRadioButtonFSaida.setVisible(false);
                jRadioButtonGSaida.setVisible(false);
                jRadioButtonHSaida.setVisible(false);

                jRadioButtonISaida.setVisible(false);
                jRadioButtonJSaida.setVisible(false);
                jRadioButtonKSaida.setVisible(false);
                jRadioButtonLSaida.setVisible(false);

                jRadioButtonMSaida.setVisible(false);
                jRadioButtonNSaida.setVisible(false);
                jRadioButtonOSaida.setVisible(false);
                jRadioButtonPSaida.setVisible(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMachineName;
    private javax.swing.JButton jButtonOperations;
    private javax.swing.JComboBox<String> jComboBoxNumberRegisters;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelConjuntos;
    private javax.swing.JLabel jLabelEntrada;
    private javax.swing.JLabel jLabelMachineName;
    private javax.swing.JLabel jLabelREntrada;
    private javax.swing.JLabel jLabelRSaida;
    private javax.swing.JLabel jLabelRegNum;
    private static javax.swing.JLabel jLabelRegisterNumber;
    private javax.swing.JLabel jLabelSaida;
    private static javax.swing.JRadioButton jRadioButtonAEntrada;
    private static javax.swing.JRadioButton jRadioButtonASaida;
    private static javax.swing.JRadioButton jRadioButtonBEntrada;
    private static javax.swing.JRadioButton jRadioButtonBSaida;
    private static javax.swing.JRadioButton jRadioButtonCEntrada;
    private static javax.swing.JRadioButton jRadioButtonCSaida;
    private static javax.swing.JRadioButton jRadioButtonDEntrada;
    private static javax.swing.JRadioButton jRadioButtonDSaida;
    private static javax.swing.JRadioButton jRadioButtonEEntrada;
    private static javax.swing.JRadioButton jRadioButtonESaida;
    private static javax.swing.JRadioButton jRadioButtonFEntrada;
    private static javax.swing.JRadioButton jRadioButtonFSaida;
    private static javax.swing.JRadioButton jRadioButtonGEntrada;
    private static javax.swing.JRadioButton jRadioButtonGSaida;
    private static javax.swing.JRadioButton jRadioButtonHEntrada;
    private static javax.swing.JRadioButton jRadioButtonHSaida;
    private static javax.swing.JRadioButton jRadioButtonIEntrada;
    private static javax.swing.JRadioButton jRadioButtonISaida;
    private static javax.swing.JRadioButton jRadioButtonJEntrada;
    private static javax.swing.JRadioButton jRadioButtonJSaida;
    private static javax.swing.JRadioButton jRadioButtonKEntrada;
    private static javax.swing.JRadioButton jRadioButtonKSaida;
    private static javax.swing.JRadioButton jRadioButtonLEntrada;
    private static javax.swing.JRadioButton jRadioButtonLSaida;
    private static javax.swing.JRadioButton jRadioButtonMEntrada;
    private static javax.swing.JRadioButton jRadioButtonMSaida;
    private static javax.swing.JRadioButton jRadioButtonNEntrada;
    private static javax.swing.JRadioButton jRadioButtonNSaida;
    private static javax.swing.JRadioButton jRadioButtonOEntrada;
    private static javax.swing.JRadioButton jRadioButtonOSaida;
    private static javax.swing.JRadioButton jRadioButtonPEntrada;
    private static javax.swing.JRadioButton jRadioButtonPSaida;
    private javax.swing.JTextField jTextFieldMachineName;
    // End of variables declaration//GEN-END:variables

}
